/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: ["./public/**/*.{html,js}"],
  theme: {
    extend: {
      colors: {
        background: "#f7fafc",
        "inverse-surface": "#2d3133",
        "surface-variant": "#e0e3e5",
        "on-tertiary-fixed": "#001f25",
        "surface-container-low": "#f1f4f6",
        "on-tertiary-container": "#4ca8ba",
        "on-tertiary": "#ffffff",
        outline: "#737780",
        "on-primary-fixed": "#001b3c",
        "on-secondary-container": "#004866",
        "surface-tint": "#3a5f94",
        "on-secondary-fixed": "#001e2d",
        "surface-bright": "#f7fafc",
        "on-error": "#ffffff",
        "surface-container-high": "#e5e9eb",
        "error-container": "#ffdad6",
        "on-background": "#181c1e",
        "on-error-container": "#93000a",
        primary: "#001e40",
        "primary-fixed-dim": "#a7c8ff",
        "surface-dim": "#d7dadc",
        "on-primary-container": "#799dd6",
        "on-tertiary-fixed-variant": "#004e5a",
        "surface-container": "#ebeef0",
        "secondary-container": "#2dbcfe",
        "secondary-fixed-dim": "#82cfff",
        tertiary: "#002228",
        "primary-fixed": "#d5e3ff",
        "secondary-fixed": "#c6e7ff",
        "outline-variant": "#c3c6d1",
        "on-secondary": "#ffffff",
        "tertiary-fixed": "#a3eeff",
        "tertiary-fixed-dim": "#7ad3e6",
        "on-secondary-fixed-variant": "#004c6b",
        "surface-container-highest": "#e0e3e5",
        "surface-container-lowest": "#ffffff",
        "on-primary": "#ffffff",
        "tertiary-container": "#003942",
        "primary-container": "#003366",
        secondary: "#00658d",
        "inverse-on-surface": "#eef1f3",
        "inverse-primary": "#a7c8ff",
        "on-surface-variant": "#43474f",
        "on-primary-fixed-variant": "#1f477b",
        error: "#ba1a1a",
        surface: "#f7fafc",
        "on-surface": "#181c1e",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        "container-max": "1280px",
        "margin-desktop": "64px",
        gutter: "24px",
        unit: "8px",
        "margin-mobile": "20px",
      },
      fontFamily: {
        "body-md": ["Work Sans", "sans-serif"],
        "body-lg": ["Work Sans", "sans-serif"],
        "headline-md": ["Hanken Grotesk", "sans-serif"],
        "label-sm": ["JetBrains Mono", "ui-monospace", "monospace"],
        "headline-lg-mobile": ["Hanken Grotesk", "sans-serif"],
        "display-lg": ["Hanken Grotesk", "sans-serif"],
        "headline-lg": ["Hanken Grotesk", "sans-serif"],
        button: ["Hanken Grotesk", "sans-serif"],
      },
      fontSize: {
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "label-sm": [
          "12px",
          { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "500" },
        ],
        "headline-lg-mobile": [
          "28px",
          { lineHeight: "36px", fontWeight: "700" },
        ],
        "display-lg": [
          "48px",
          { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "800" },
        ],
        "headline-lg": ["32px", { lineHeight: "40px", fontWeight: "700" }],
        button: [
          "14px",
          { lineHeight: "20px", letterSpacing: "0.02em", fontWeight: "600" },
        ],
      },
    },
  },
  plugins: [
    require("@tailwindcss/forms"),
    require("@tailwindcss/container-queries"),
  ],
};
